/* eslint-disable react-hooks/immutability, react-hooks/exhaustive-deps, prefer-const */
"use client";

import { useCallback, useEffect, useRef, useState } from "react";

const W=1280,H=720,WORLD=4300,FLOOR=610,GRAVITY=2100;
type Kind="player"|"goblin"|"slime"|"boss";
type Actor={kind:Kind;x:number;y:number;vx:number;vy:number;w:number;h:number;hp:number;maxHp:number;face:number;ground:boolean;state:string;timer:number;cool:number;inv:number;dead:boolean;hit:Set<number>};
type Platform={x:number;y:number;w:number;h:number};
type Game={player:Actor; enemies:Actor[]; keys:Set<string>; time:number; camera:number; particles:{x:number;y:number;vx:number;vy:number;life:number;color:string}[]; victory:boolean; shake:number};
const sheets={player:"/assets/adventurer-core-spritesheet-v1.png",move:"/assets/adventurer-traversal-spritesheet-v1.png",action:"/assets/adventurer-expanded-actions-spritesheet-v1.png",react:"/assets/adventurer-reactions-defeat-spritesheet-v1.png",goblin:"/assets/enemy-goblin-scout-spritesheet-v1.png",slime:"/assets/enemy-forest-slime-spritesheet-v1.png",boss:"/assets/boss-goblin-warchief-core-spritesheet-v1.png",woods:"/assets/biome-woodland-example-encounter-v1.png"};
const platforms:Platform[]=[{x:0,y:FLOOR,w:WORLD,h:160},{x:410,y:505,w:250,h:26},{x:810,y:445,w:210,h:26},{x:1230,y:520,w:270,h:26},{x:1660,y:460,w:230,h:26},{x:2050,y:395,w:190,h:26},{x:2390,y:505,w:300,h:26},{x:2890,y:450,w:230,h:26},{x:3260,y:525,w:230,h:26}];
const make=(kind:Kind,x:number,y=450):Actor=>({kind,x,y,vx:0,vy:0,w:kind==="boss"?86:50,h:kind==="boss"?110:72,hp:kind==="boss"?240:kind==="player"?100:55,maxHp:kind==="boss"?240:kind==="player"?100:55,face:-1,ground:false,state:"idle",timer:0,cool:0,inv:0,dead:false,hit:new Set()});

export default function GameCanvas(){
 const canvas=useRef<HTMLCanvasElement>(null); const game=useRef<Game|null>(null); const imgs=useRef<Record<string,HTMLImageElement>>({}); const raf=useRef(0); const last=useRef(0); const [started,setStarted]=useState(false);
 const reset=useCallback(()=>{game.current={player:make("player",120),enemies:[make("slime",720),make("goblin",1120),make("slime",1580),make("goblin",1960),make("goblin",2590),make("slime",3020),make("boss",3760,420)],keys:new Set(),time:0,camera:0,particles:[],victory:false,shake:0};setStarted(true)},[]);
 const press=(k:string,on:boolean)=>{const g=game.current;if(!g)return;if(on)g.keys.add(k);else g.keys.delete(k)};
 useEffect(()=>{for(const [k,v] of Object.entries(sheets)){const im=new Image();im.src=v;imgs.current[k]=im}const kd=(e:KeyboardEvent)=>{if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();press(e.code,true)};const ku=(e:KeyboardEvent)=>press(e.code,false);addEventListener("keydown",kd);addEventListener("keyup",ku);return()=>{removeEventListener("keydown",kd);removeEventListener("keyup",ku)}},[]);
 useEffect(()=>{if(!started)return;const loop=(t:number)=>{const dt=Math.min((t-last.current)/1000||0,.033);last.current=t;update(dt);draw();raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[started]);
 function attack(a:Actor,state:string,dur:number){if(a.cool>0||a.dead)return;a.state=state;a.timer=dur;a.cool=dur+.12;a.vx*=.3;a.hit.clear()}
 function particles(g:Game,x:number,y:number,color="#ef7a3d"){for(let i=0;i<8;i++)g.particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.8)*240,life:.45,color})}
 function damage(g:Game,a:Actor,n:number,dir:number){if(a.inv>0||a.dead)return;a.hp-=n;a.inv=.28;a.vx=dir*260;a.vy=-180;a.state="hurt";a.timer=.28;particles(g,a.x,a.y-a.h/2,a.kind==="player"?"#e7ddc4":"#ef7a3d");g.shake=10;if(a.hp<=0){a.hp=0;a.dead=true;a.state="dead";a.timer=2}}
 function physics(a:Actor,dt:number){a.vy+=GRAVITY*dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.ground=false;for(const p of platforms){if(a.x+a.w/2>p.x&&a.x-a.w/2<p.x+p.w&&a.y>=p.y&&a.y-a.vy*dt<=p.y+8&&a.vy>=0){a.y=p.y;a.vy=0;a.ground=true}}a.x=Math.max(25,Math.min(WORLD-25,a.x));if(a.y>800){a.y=300;a.vy=0;if(a.kind==="player")a.hp=Math.max(1,a.hp-20)}}
 function update(dt:number){const g=game.current;if(!g)return;g.time+=dt;g.shake=Math.max(0,g.shake-30*dt);const p=g.player;p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.timer-=dt;
  if(p.dead){if(p.timer<=0)reset();return}const left=g.keys.has("KeyA")||g.keys.has("ArrowLeft"),right=g.keys.has("KeyD")||g.keys.has("ArrowRight");
  if(p.state==="dodge"){p.vx=p.face*620}else if(!["slash","heavy","hurt"].includes(p.state)){p.vx=((right?1:0)-(left?1:0))*310;if(p.vx)p.face=Math.sign(p.vx);p.state=p.ground?(p.vx?"run":"idle"):"jump"}
  if((g.keys.has("Space")||g.keys.has("KeyW")||g.keys.has("ArrowUp"))&&p.ground&&p.cool<=0){p.vy=-780;p.ground=false;p.state="jump";p.cool=.2}
  if(g.keys.has("KeyJ"))attack(p,"slash",.42);if(g.keys.has("KeyK"))attack(p,"heavy",.7);if(g.keys.has("KeyL")&&p.cool<=0){p.state="dodge";p.timer=.38;p.cool=.7;p.inv=.48}
  if(p.timer<=0&&["slash","heavy","dodge","hurt"].includes(p.state))p.state=p.ground?"idle":"jump";physics(p,dt);
  for(let i=0;i<g.enemies.length;i++){const e=g.enemies[i];if(e.dead)continue;e.cool=Math.max(0,e.cool-dt);e.inv=Math.max(0,e.inv-dt);e.timer-=dt;const dx=p.x-e.x,ad=Math.abs(dx);e.face=Math.sign(dx)||e.face;
   if(e.timer<=0&&["attack","hurt"].includes(e.state))e.state="idle";
   if(e.state==="attack"&&e.timer<.28&&ad<(e.kind==="boss"?145:88)&&Math.abs(p.y-e.y)<90&&!e.hit.has(0)){damage(g,p,e.kind==="boss"?24:12,e.face);e.hit.add(0)}
   else if(!["attack","hurt"].includes(e.state)){if(ad<(e.kind==="boss"?180:105)&&e.cool<=0){e.state="attack";e.timer=e.kind==="boss"?.85:.62;e.cool=e.kind==="boss"?1.5:1.15;e.hit.clear();e.vx=0}else if(ad<620){e.state="run";e.vx=e.face*(e.kind==="boss"?105:e.kind==="slime"?85:125)}else{e.state="idle";e.vx=0}}
   if((p.state==="slash"||p.state==="heavy")&&p.timer<(p.state==="heavy"?.42:.28)&&Math.abs(dx)<(p.state==="heavy"?130:94)&&Math.abs(p.y-e.y)<90&&Math.sign(dx)===p.face&&!p.hit.has(i)){damage(g,e,p.state==="heavy"?36:22,p.face);p.hit.add(i)}physics(e,dt)}
  g.victory=g.enemies.find(e=>e.kind==="boss")?.dead||false;g.camera+=(Math.max(0,Math.min(WORLD-W,p.x-W*.38))-g.camera)*Math.min(1,dt*5);for(const q of g.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=800*dt;q.life-=dt}g.particles=g.particles.filter(q=>q.life>0)
 }
 function sprite(ctx:CanvasRenderingContext2D,a:Actor){let key=a.kind,row=0,frames=6;if(a.kind==="player"){if(a.state==="run"||a.state==="jump"){key="move";row=a.state==="run"?0:1}else if(a.state==="dodge"||a.state==="heavy"){key="action";row=a.state==="heavy"?0:2}else if(a.state==="hurt"||a.state==="dead"){key="react";row=a.state==="hurt"?0:3}else row=a.state==="slash"?2:0}else row=a.state==="run"?1:a.state==="attack"?2:a.state==="hurt"||a.dead?3:0;const im=imgs.current[key];if(!im?.complete)return;const frame=Math.floor(game.current!.time*(a.state==="idle"?5:10))%frames;const size=a.kind==="boss"?190:112;ctx.save();ctx.translate(a.x,a.y);ctx.scale(a.face,1);if(a.inv>0&&Math.floor(a.inv*30)%2)ctx.globalAlpha=.35;ctx.drawImage(im,frame*256,row*256,256,256,-size/2,-size*.88,size,size);ctx.restore()}
 function draw(){const c=canvas.current,g=game.current;if(!c||!g)return;const x=c.getContext("2d")!;x.imageSmoothingEnabled=false;x.clearRect(0,0,W,H);const shake=g.shake?(Math.random()-.5)*g.shake:0;x.save();x.translate(shake,0);const bg=imgs.current.woods;if(bg?.complete){for(let i=-1;i<7;i++)x.drawImage(bg,i*768-(g.camera*.16%768),0,768,H)}x.fillStyle="#07100a77";x.fillRect(0,0,W,H);x.save();x.translate(-g.camera,0);
  for(const p of platforms){x.fillStyle="#101710";x.fillRect(p.x,p.y,p.w,p.h);x.fillStyle="#64734c";x.fillRect(p.x,p.y,p.w,7);for(let i=p.x+12;i<p.x+p.w;i+=34){x.fillStyle="#33412d";x.fillRect(i,p.y+8,17,5)}}
  for(const e of g.enemies)sprite(x,e);sprite(x,g.player);for(const q of g.particles){x.globalAlpha=q.life/.45;x.fillStyle=q.color;x.fillRect(q.x,q.y,6,6)}x.globalAlpha=1;x.restore();
  x.fillStyle="#0b100dc9";x.fillRect(28,26,340,72);x.fillStyle="#e7ddc4";x.font="700 18px Cinzel";x.fillText("THE WAYFARER",48,53);x.fillStyle="#3a2925";x.fillRect(48,67,280,12);x.fillStyle=g.player.hp<30?"#cf4935":"#ef7a3d";x.fillRect(48,67,280*g.player.hp/g.player.maxHp,12);x.strokeStyle="#e7ddc455";x.strokeRect(48,67,280,12);
  const boss=g.enemies.find(e=>e.kind==="boss"&&!e.dead);if(boss&&Math.abs(boss.x-g.player.x)<800){x.fillStyle="#080b09dd";x.fillRect(370,40,540,55);x.textAlign="center";x.fillStyle="#e7ddc4";x.font="700 18px Cinzel";x.fillText("GORRAK, WARCHIEF OF THE BRIAR",640,65);x.fillStyle="#371c19";x.fillRect(425,76,430,8);x.fillStyle="#b84d32";x.fillRect(425,76,430*boss.hp/boss.maxHp,8);x.textAlign="left"}
  if(g.victory){x.fillStyle="#07100bd9";x.fillRect(0,0,W,H);x.textAlign="center";x.fillStyle="#ef7a3d";x.font="800 72px Cinzel";x.fillText("ROAD CLEARED",W/2,310);x.fillStyle="#e7ddc4";x.font="600 18px IBM Plex Mono";x.fillText("The old gate wakes. Your journey continues.",W/2,355);x.textAlign="left"}x.restore()
 }
 const touch=(code:string)=>(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();press(code,e.type==="pointerdown")};
 return <div className="game-wrap"><canvas ref={canvas} width={W} height={H}/>{!started&&<div className="start-card"><p>A hand-forged action prototype</p><h1><span>EMBER</span>WAKE</h1><p>Cross the Mossbound Road</p><button onClick={reset}>Enter the wilds</button></div>}<div className="touch"><div><button onPointerDown={touch("KeyA")} onPointerUp={touch("KeyA")} onPointerCancel={touch("KeyA")}>←</button><button onPointerDown={touch("KeyD")} onPointerUp={touch("KeyD")} onPointerCancel={touch("KeyD")}>→</button><button onPointerDown={touch("Space")} onPointerUp={touch("Space")}>↑</button></div><div><button onPointerDown={touch("KeyJ")} onPointerUp={touch("KeyJ")}>J</button><button onPointerDown={touch("KeyK")} onPointerUp={touch("KeyK")}>K</button><button onPointerDown={touch("KeyL")} onPointerUp={touch("KeyL")}>L</button></div></div></div>
}
