/* eslint-disable react-hooks/immutability, react-hooks/exhaustive-deps */
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { attackDamage, fieldGrade } from "./mechanics";

const W=1280,H=720,WORLD=5000,FLOOR=610,G=2200;
type Kind="player"|"goblin"|"slime"|"boss";
type Actor={id:number;kind:Kind;x:number;y:number;vx:number;vy:number;w:number;h:number;hp:number;maxHp:number;face:number;ground:boolean;coyote:number;jumpBuffer:number;state:string;timer:number;cool:number;inv:number;dead:boolean;hit:Set<number>;phase:number};
type Spark={x:number;y:number;vx:number;vy:number;life:number;max:number;color:string;size:number};
type Wave={x:number;y:number;vx:number;life:number;hit:boolean};
type FloatText={x:number;y:number;value:number|string;life:number;heavy:boolean;color?:string};
type Shard={x:number;y:number;taken:boolean};
type Toast={text:string;sub:string;life:number};
type Game={player:Actor;enemies:Actor[];shards:Shard[];embers:number;keys:Set<string>;pressed:Set<string>;pad:Set<string>;time:number;camera:number;sparks:Spark[];waves:Wave[];floats:FloatText[];victory:boolean;victorySaved:boolean;practice:boolean;bossSeen:boolean;shake:number;hitstop:number;stamina:number;combo:number;comboTime:number;kills:number;checkpoint:number;toast:Toast|null;paused:boolean;muted?:boolean;startedAt:number;attackBuffer:string;attackBufferTime:number;perfectDodges:number;bestTime:number;bestEmbers:number};
const sheets={player:"/assets/adventurer-core-spritesheet-v1.png",move:"/assets/adventurer-traversal-spritesheet-v1.png",action:"/assets/adventurer-expanded-actions-spritesheet-v1.png",react:"/assets/adventurer-reactions-defeat-spritesheet-v1.png",goblin:"/assets/enemy-goblin-scout-spritesheet-v1.png",slime:"/assets/enemy-forest-slime-spritesheet-v1.png",boss:"/assets/boss-goblin-warchief-core-spritesheet-v1.png",bossSpecial:"/assets/boss-goblin-warchief-special-spritesheet-v1.png",forest:"/assets/mossbound-forest-loop-v2.png",gate:"/assets/mossbound-road-background-v2.png"};
const platforms=[{x:0,y:FLOOR,w:720,h:160},{x:790,y:FLOOR,w:690,h:160},{x:1550,y:FLOOR,w:720,h:160},{x:2340,y:FLOOR,w:640,h:160},{x:3060,y:FLOOR,w:620,h:160},{x:3740,y:FLOOR,w:1260,h:160},{x:420,y:500,w:210,h:22},{x:905,y:470,w:190,h:22},{x:1190,y:410,w:180,h:22},{x:1690,y:495,w:220,h:22},{x:2020,y:430,w:180,h:22},{x:2460,y:490,w:240,h:22},{x:2820,y:425,w:130,h:22},{x:3190,y:480,w:210,h:22}];
const hazards=[{x:720,w:70},{x:1480,w:70},{x:2270,w:70},{x:2980,w:80},{x:3680,w:60}];
const checkpoints=[120,1580,3100,3820];
let nextId=1;
const make=(kind:Kind,x:number,y=450):Actor=>({id:nextId++,kind,x,y,vx:0,vy:0,w:kind==="boss"?96:52,h:kind==="boss"?118:74,hp:kind==="boss"?360:kind==="player"?100:kind==="slime"?42:64,maxHp:kind==="boss"?360:kind==="player"?100:kind==="slime"?42:64,face:kind==="player"?1:-1,ground:false,coyote:0,jumpBuffer:0,state:"idle",timer:0,cool:0,inv:0,dead:false,hit:new Set(),phase:1});

export default function GameCanvas(){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef<Game|null>(null),imgs=useRef<Record<string,HTMLImageElement>>({}),audio=useRef<AudioContext|null>(null),muted=useRef(false),reducedMotion=useRef(false),raf=useRef(0),last=useRef(0);const [started,setStarted]=useState(false),[ready,setReady]=useState(false);
 const tone=(freq:number,dur=.07,type:OscillatorType="square",gain=.035)=>{const ac=audio.current;if(!ac||muted.current)return;const o=ac.createOscillator(),v=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,ac.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(45,freq*.55),ac.currentTime+dur);v.gain.setValueAtTime(gain,ac.currentTime);v.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+dur);o.connect(v);v.connect(ac.destination);o.start();o.stop(ac.currentTime+dur)};
 const reset=useCallback(()=>{audio.current??=new AudioContext();nextId=1;const savedTime=Number(localStorage.getItem("emberwake-best-time"))||0,savedEmbers=Number(localStorage.getItem("emberwake-best-embers"))||0;game.current={player:make("player",120),enemies:[make("slime",600),make("goblin",980),make("goblin",1350),make("slime",1800),make("goblin",2140),make("slime",2570),make("goblin",2870),make("goblin",3350),make("slime",3540),make("boss",4450,480)],shards:[{x:520,y:455,taken:false},{x:995,y:425,taken:false},{x:1280,y:365,taken:false},{x:1790,y:450,taken:false},{x:2110,y:385,taken:false},{x:3290,y:435,taken:false}],embers:0,keys:new Set(),pressed:new Set(),pad:new Set(),time:0,camera:0,sparks:[],waves:[],floats:[],victory:false,victorySaved:false,practice:false,bossSeen:false,shake:0,hitstop:0,stamina:100,combo:0,comboTime:0,kills:0,checkpoint:120,toast:{text:"THE MOSSBOUND ROAD",sub:"Reach the gate beyond the briars",life:3.6},paused:false,startedAt:performance.now(),attackBuffer:"",attackBufferTime:0,perfectDodges:0,bestTime:savedTime,bestEmbers:savedEmbers};last.current=performance.now();tone(180,.12,"triangle",.045);setStarted(true)},[]);
 const key=(code:string,on:boolean)=>{const g=game.current;if(!g)return;if(on){if(!g.keys.has(code))g.pressed.add(code);g.keys.add(code)}else g.keys.delete(code)};
 useEffect(()=>{muted.current=localStorage.getItem("emberwake-muted")==="1";let loaded=0;const done=()=>{loaded++;if(loaded===Object.keys(sheets).length)setReady(true)};for(const [k,v] of Object.entries(sheets)){const im=new Image();im.onload=done;im.onerror=done;im.src=v;imgs.current[k]=im}const motion=matchMedia("(prefers-reduced-motion: reduce)"),syncMotion=()=>reducedMotion.current=motion.matches;syncMotion();motion.addEventListener("change",syncMotion);const down=(e:KeyboardEvent)=>{if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();key(e.code,true)};const up=(e:KeyboardEvent)=>key(e.code,false);const blur=()=>{const g=game.current;if(g){g.keys.clear();g.pressed.clear();if(!g.victory)g.paused=true}};addEventListener("keydown",down);addEventListener("keyup",up);addEventListener("blur",blur);return()=>{motion.removeEventListener("change",syncMotion);removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("blur",blur)}},[]);

 function burst(g:Game,x:number,y:number,color="#ef7a3d",count=9){const total=reducedMotion.current?Math.ceil(count*.35):count;for(let i=0;i<total;i++){const life=.25+Math.random()*.35;g.sparks.push({x,y,vx:(Math.random()-.5)*310,vy:(Math.random()-.85)*280,life,max:life,color,size:3+Math.random()*5})}}
 function attack(a:Actor,state:string,dur:number,cost=0){const g=game.current;if(!g||a.dead)return false;if(a.cool>0||g.stamina<cost){g.attackBuffer=state;g.attackBufferTime=.18;return false}a.state=state;a.timer=dur;a.cool=dur+.1;a.vx*=.22;a.hit.clear();g.stamina-=cost;g.attackBuffer="";g.attackBufferTime=0;tone(state==="heavy"?105:170,state==="heavy"?.16:.08,"sawtooth",.025);return true}
 function perfectDodge(g:Game,e:Actor){if(g.player.state!=="dodge"||e.hit.has(-99))return;e.hit.add(-99);g.perfectDodges++;g.stamina=Math.min(100,g.stamina+30);g.hitstop=.055;g.shake=5;g.floats.push({x:g.player.x,y:g.player.y-92,value:"EMBERSTEP",life:.9,heavy:true,color:"#8ee8d2"});tone(620,.12,"sine",.035);burst(g,g.player.x,g.player.y-40,"#8ee8d2",16)}
 function hurt(g:Game,a:Actor,n:number,dir:number){if(a.inv>0||a.dead)return;a.hp=Math.max(0,a.hp-n);a.inv=a.kind==="player"?.48:.22;a.vx=dir*300;a.vy=-200;a.state="hurt";a.timer=.28;g.shake=a.kind==="boss"?8:12;g.hitstop=a.kind==="boss"?.055:a.kind==="player"?.08:.04;tone(a.kind==="player"?75:120,a.kind==="boss"?.12:.07,"square",.045);burst(g,a.x,a.y-a.h*.5,a.kind==="player"?"#e7ddc4":"#ff7a3c",a.kind==="boss"?15:9);g.floats.push({x:a.x,y:a.y-a.h,value:n,life:.75,heavy:n>=30});if(a.kind==="player"){g.combo=0;g.comboTime=0}else{g.combo++;g.comboTime=2.2}if(a.hp===0){a.dead=true;a.state="dead";a.timer=a.kind==="player"?1.6:1;if(a.kind!=="player"){g.kills++;g.stamina=Math.min(100,g.stamina+18);g.player.hp=Math.min(100,g.player.hp+(a.kind==="boss"?20:5))}tone(58,.28,"sawtooth",.05);burst(g,a.x,a.y-a.h*.4,"#d7b45b",20)}}
 function land(a:Actor,oldY:number){a.ground=false;for(const p of platforms){if(a.x+a.w*.35>p.x&&a.x-a.w*.35<p.x+p.w&&a.y>=p.y&&oldY<=p.y+7&&a.vy>=0){a.y=p.y;a.vy=0;a.ground=true;break}}}
 function physics(g:Game,a:Actor,dt:number){const oldY=a.y,wasGround=a.ground,fallSpeed=a.vy;a.vy+=G*dt;a.x+=a.vx*dt;a.y+=a.vy*dt;land(a,oldY);if(a.kind==="player"&&!wasGround&&a.ground&&fallSpeed>420){burst(g,a.x,a.y-2,"#8a9c78",Math.min(9,4+Math.floor(fallSpeed/180)));if(fallSpeed>720)g.shake=Math.max(g.shake,3)}const gateLocked=a.kind==="player"&&g.bossSeen&&!g.victory&&g.enemies.some(e=>e.kind==="boss"&&!e.dead);a.x=Math.max(a.kind==="boss"||gateLocked?3820:24,Math.min(WORLD-24,a.x));if(a.y>780){if(a.kind==="player"){a.x=g.checkpoint;a.y=350;a.vx=0;a.vy=0;hurt(g,a,18,0)}else if(!a.dead){a.dead=true;a.timer=0;g.kills++}}}
 function pollPad(g:Game){const p=navigator.getGamepads?.()[0];if(!p)return;const active=new Set<string>();if(p.axes[0]<-.28)active.add("KeyA");if(p.axes[0]>.28)active.add("KeyD");if(p.buttons[0]?.pressed)active.add("Space");if(p.buttons[2]?.pressed)active.add("KeyJ");if(p.buttons[3]?.pressed)active.add("KeyK");if(p.buttons[1]?.pressed)active.add("KeyL");if(p.buttons[9]?.pressed)active.add("Escape");for(const code of active){if(!g.pad.has(code))g.pressed.add(code);g.keys.add(code)}for(const code of g.pad)if(!active.has(code))g.keys.delete(code);g.pad=active}
 function tick(dt:number){const g=game.current;if(!g)return;g.muted=muted.current;pollPad(g);if(g.victory){if(g.pressed.has("Enter")||g.pressed.has("Space")){reset();return}g.pressed.clear();return}if(g.pressed.has("KeyM")){muted.current=!muted.current;localStorage.setItem("emberwake-muted",muted.current?"1":"0");g.muted=muted.current;g.toast={text:g.muted?"SOUND MUTED":"SOUND RESTORED",sub:"Press M to toggle field audio",life:1.7};if(!g.muted)tone(320,.08,"sine",.025)}if(g.pressed.has("Escape"))g.paused=!g.paused;if(g.paused){g.pressed.clear();return}if(g.hitstop>0){g.hitstop-=dt;return}g.time+=dt;g.shake=Math.max(0,g.shake-38*dt);g.stamina=Math.min(100,g.stamina+28*dt);g.comboTime-=dt;g.attackBufferTime=Math.max(0,g.attackBufferTime-dt);if(g.attackBufferTime<=0)g.attackBuffer="";if(g.comboTime<=0)g.combo=0;if(g.toast){g.toast.life-=dt;if(g.toast.life<=0)g.toast=null}
  const p=g.player;p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.timer-=dt;p.coyote=p.ground?.11:Math.max(0,p.coyote-dt);p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);if(g.pressed.has("Space")||g.pressed.has("KeyW")||g.pressed.has("ArrowUp"))p.jumpBuffer=.13;if(p.dead){if(p.timer<=0){p.dead=false;p.hp=100;p.x=g.checkpoint;p.y=350;p.state="idle";p.inv=1;const b=g.enemies.find(e=>e.kind==="boss");if(b&&!b.dead&&g.checkpoint>=3820){b.x=4350;b.y=480;b.vx=0;b.vy=0;b.hp=b.maxHp;b.phase=1;b.state="idle";b.cool=.8;b.hit.clear();g.waves=[]}g.toast={text:"EMBER REKINDLED",sub:g.checkpoint>=3820?"The Warchief awaits a clean rematch":"The road remembers your steps",life:2.5}}g.pressed.clear();return}
  const left=g.keys.has("KeyA")||g.keys.has("ArrowLeft")||g.pressed.has("KeyA")||g.pressed.has("ArrowLeft"),right=g.keys.has("KeyD")||g.keys.has("ArrowRight")||g.pressed.has("KeyD")||g.pressed.has("ArrowRight");if(p.state==="dodge")p.vx=p.face*690;else if(!["slash","heavy","hurt"].includes(p.state)){const target=((right?1:0)-(left?1:0))*330;p.vx+=(target-p.vx)*Math.min(1,dt*(p.ground?18:7));if(Math.abs(p.vx)>10)p.face=Math.sign(p.vx);p.state=p.ground?(Math.abs(p.vx)>35?"run":"idle"):"jump"}
  if(!left&&!right&&(g.pressed.has("KeyJ")||g.pressed.has("KeyK"))){const near=g.enemies.filter(e=>!e.dead&&Math.abs(e.x-p.x)<230).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];if(near)p.face=Math.sign(near.x-p.x)||p.face}
  if(p.jumpBuffer>0&&p.coyote>0){p.vy=-815;p.ground=false;p.coyote=0;p.jumpBuffer=0;p.state="jump";tone(210,.08,"triangle",.02);burst(g,p.x,p.y,"#92a57a",5)}if(!g.keys.has("Space")&&!g.keys.has("KeyW")&&!g.keys.has("ArrowUp")&&p.vy<-250)p.vy+=G*1.25*dt;if(g.pressed.has("KeyJ"))attack(p,"slash",.38);if(g.pressed.has("KeyK"))attack(p,"heavy",.67,28);const dodgeCancel=(p.state==="slash"&&p.timer<.2)||(p.state==="heavy"&&p.timer<.3);if(g.pressed.has("KeyL")&&(p.cool<=0||dodgeCancel)&&g.stamina>=24){p.state="dodge";p.timer=.34;p.cool=.62;p.inv=.43;p.hit.clear();g.attackBuffer="";g.stamina-=24;tone(260,.06,"triangle",.018);burst(g,p.x,p.y-30,"#80a9a0",7)}if(p.cool<=0&&g.attackBufferTime>0){if(g.attackBuffer==="heavy")attack(p,"heavy",.67,28);else if(g.attackBuffer==="slash")attack(p,"slash",.38)}if(p.timer<=0&&["slash","heavy","dodge","hurt"].includes(p.state))p.state=p.ground?"idle":"jump";physics(g,p,dt);
  for(const cp of checkpoints)if(p.x>cp&&cp>g.checkpoint){g.checkpoint=cp;g.toast={text:cp===1580?"THE DROWNED SHRINE":"THE BRIAR APPROACH",sub:"Wayside ember bound · vitality restored",life:2.4};p.hp=Math.min(100,p.hp+25);burst(g,cp,FLOOR-40,"#ef9c4a",24)}if(p.x>3650&&!g.bossSeen){g.bossSeen=true;g.checkpoint=3820;g.toast={text:"THE OLD GATE",sub:"Gorrak, Warchief of the Briar",life:3};tone(72,.3,"sawtooth",.04)}
  for(const shard of g.shards)if(!shard.taken&&Math.abs(p.x-shard.x)<42&&Math.abs(p.y-shard.y)<62){shard.taken=true;g.embers++;p.hp=Math.min(100,p.hp+7);g.stamina=Math.min(100,g.stamina+20);tone(540,.16,"sine",.035);burst(g,shard.x,shard.y,"#f6c56f",18);g.toast=g.embers===g.shards.length?{text:"EMBER CACHE RESTORED",sub:"Every hidden spark answers your blade",life:2.8}:{text:"EMBER BOUND",sub:`Blade power +${g.embers} · cache ${g.embers}/${g.shards.length}`,life:1.35}}
  for(const e of g.enemies)if(e.dead){e.timer-=dt;if(e.timer>0)physics(g,e,dt)}
  for(const e of g.enemies){if(e.dead)continue;e.cool=Math.max(0,e.cool-dt);e.inv=Math.max(0,e.inv-dt);e.timer-=dt;const dx=p.x-e.x,ad=Math.abs(dx);e.face=Math.sign(dx)||e.face;if(e.kind==="boss"){const phase=e.hp/e.maxHp<.34?3:e.hp/e.maxHp<.68?2:1;if(phase!==e.phase){e.phase=phase;e.inv=.7;g.toast={text:phase===2?"GORRAK BREAKS HIS CHAINS":"THE WARCHIEF ENRAGES",sub:phase===2?"His reach grows longer":"Do not trade blows",life:2.5};burst(g,e.x,e.y-70,"#ef7a3d",30)}}
   if(e.kind==="boss"&&e.phase===3&&e.state==="attack"&&e.timer<.58&&!e.hit.has(-1)){g.waves.push({x:e.x+e.face*70,y:e.y-8,vx:e.face*520,life:1.25,hit:false});e.hit.add(-1);tone(66,.22,"sawtooth",.045);g.shake=8}
   if(e.timer<=0&&["attack","hurt","charge"].includes(e.state))e.state="idle";if((e.state==="attack"||e.state==="charge")&&e.timer<(e.kind==="boss"?.38:.24)&&ad<(e.kind==="boss"?155:92)&&Math.abs(p.y-e.y)<105&&p.state==="dodge")perfectDodge(g,e);if((e.state==="attack"||e.state==="charge")&&e.timer<(e.kind==="boss"?.38:.24)&&ad<(e.kind==="boss"?145:82)&&Math.abs(p.y-e.y)<100&&!e.hit.has(p.id)){hurt(g,p,e.kind==="boss"?(e.phase===3?28:22):e.kind==="slime"?8:11,e.face);e.hit.add(p.id)}else if(!["attack","hurt","charge"].includes(e.state)){const sight=e.kind==="boss"?800:e.kind==="slime"?420:520;if(ad<(e.kind==="boss"?190:100)&&e.cool<=0){e.state="attack";e.timer=e.kind==="boss"?.78:.56;e.cool=e.kind==="boss"?Math.max(.75,1.4-e.phase*.12):1.05;e.hit.clear();e.vx=0}else if(e.kind==="boss"&&e.phase>1&&ad>300&&ad<680&&e.cool<=0){e.state="charge";e.timer=.72;e.cool=1.5;e.hit.clear();e.vx=e.face*(e.phase===3?520:420)}else if(ad<sight){e.state="run";e.vx=e.face*(e.kind==="boss"?115:e.kind==="slime"?82:132);if(e.kind==="slime"&&e.ground&&e.cool<=0){e.vy=-430;e.cool=.7;burst(g,e.x,e.y,"#8dbb63",4)}}else{e.state="idle";e.vx*=.8}}
   const active=p.state==="slash"||p.state==="heavy";if(active&&p.timer<(p.state==="heavy"?.43:.25)&&Math.abs(dx)<(p.state==="heavy"?205:112)+e.w*.55&&Math.abs(p.y-e.y)<100&&Math.sign(-dx)===p.face&&!p.hit.has(e.id)){hurt(g,e,attackDamage(p.state,g.embers),p.face);p.hit.add(e.id)}physics(g,e,dt)}
  for(const w of g.waves){w.x+=w.vx*dt;w.life-=dt;if(!w.hit&&Math.abs(w.x-p.x)<48&&Math.abs(w.y-p.y)<76&&p.state==="dodge"){w.hit=true;g.perfectDodges++;g.stamina=Math.min(100,g.stamina+25);g.floats.push({x:p.x,y:p.y-92,value:"FLAME CLEAVED",life:.9,heavy:true,color:"#8ee8d2"});tone(660,.1,"sine",.03);burst(g,p.x,p.y-35,"#8ee8d2",14)}else if(!w.hit&&Math.abs(w.x-p.x)<42&&Math.abs(w.y-p.y)<70){hurt(g,p,18,Math.sign(w.vx));w.hit=true}}g.waves=g.waves.filter(w=>w.life>0);const boss=g.enemies.find(e=>e.kind==="boss");if(boss?.dead&&!g.victory){g.victory=true;g.toast=null}if(g.victory&&!g.victorySaved){g.victorySaved=true;const seconds=Math.floor(g.time);if(!g.practice){if(!g.bestTime||seconds<g.bestTime){g.bestTime=seconds;localStorage.setItem("emberwake-best-time",String(seconds))}if(g.embers>g.bestEmbers){g.bestEmbers=g.embers;localStorage.setItem("emberwake-best-embers",String(g.embers))}}}g.camera+=(Math.max(0,Math.min(WORLD-W,p.x-W*.35))-g.camera)*Math.min(1,dt*5.5);for(const s of g.sparks){s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=700*dt;s.life-=dt}g.sparks=g.sparks.filter(s=>s.life>0);for(const f of g.floats){f.y-=42*dt;f.life-=dt}g.floats=g.floats.filter(f=>f.life>0);g.pressed.clear()
 }
 function sprite(ctx:CanvasRenderingContext2D,a:Actor){let key:string=a.kind,row=0;if(a.kind==="player"){if(a.state==="run"||a.state==="jump"){key="move";row=a.state==="run"?0:1}else if(a.state==="heavy"||a.state==="dodge"){key="action";row=a.state==="heavy"?0:2}else if(a.state==="hurt"||a.state==="dead"){key="react";row=a.state==="hurt"?0:3}else row=a.state==="slash"?2:0}else{if(a.kind==="boss"&&a.phase===3)key="bossSpecial";row=a.state==="run"?1:a.state==="attack"||a.state==="charge"?2:a.state==="hurt"||a.dead?3:0}const im=imgs.current[key];if(!im?.complete)return;const frame=Math.floor((game.current!.time+(a.id*.07))*(a.state==="idle"?5:11))%6,size=a.kind==="boss"?210:118;ctx.save();ctx.translate(Math.round(a.x),Math.round(a.y));if(a.dead){ctx.globalAlpha=Math.max(0,a.timer);ctx.rotate(a.face*.72)}ctx.scale(a.kind==="player"?-a.face:a.face,1);if(a.inv>0&&Math.floor(a.inv*30)%2)ctx.globalAlpha=.3;ctx.drawImage(im,frame*256,row*256,256,256,-size/2,-size*.9,size,size);ctx.restore()}
function bar(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,value:number,color:string){ctx.fillStyle="#0a0e0cdd";ctx.fillRect(x,y,w,10);ctx.fillStyle=color;ctx.fillRect(x+2,y+2,(w-4)*Math.max(0,value),6)}
 function landmarks(ctx:CanvasRenderingContext2D,g:Game){ctx.save();ctx.globalAlpha=.72;ctx.fillStyle="#172019";ctx.fillRect(1575,350,54,260);ctx.fillRect(2210,405,46,205);ctx.fillStyle="#344238";ctx.fillRect(1567,342,70,15);ctx.fillRect(2202,397,62,13);ctx.fillStyle="#526253";for(let y=372;y<585;y+=42){ctx.fillRect(1584,y,34,4);ctx.fillRect(2218,y+12,29,4)}ctx.strokeStyle="#3f5848";ctx.lineWidth=12;ctx.beginPath();ctx.arc(1915,505,240,Math.PI*1.08,Math.PI*1.92);ctx.stroke();ctx.lineWidth=4;ctx.strokeStyle="#6a795f";ctx.beginPath();ctx.moveTo(1628,445);ctx.quadraticCurveTo(1850,535,2208,466);ctx.stroke();ctx.globalAlpha=.16;ctx.fillStyle="#89b3a4";for(let i=0;i<8;i++){const drift=Math.sin(g.time*.3+i)*18;ctx.fillRect(1580+i*88+drift,552+(i%3)*9,130,5)}ctx.globalAlpha=.8;ctx.fillStyle="#151c16";for(const bx of [3040,3525]){ctx.fillRect(bx,375,24,235);ctx.beginPath();ctx.moveTo(bx-38,420);ctx.lineTo(bx+12,355);ctx.lineTo(bx+62,420);ctx.lineTo(bx+12,395);ctx.fill();ctx.strokeStyle="#506348";ctx.lineWidth=5;for(let y=420;y<585;y+=36){ctx.beginPath();ctx.moveTo(bx+4,y);ctx.lineTo(bx-22,y-22);ctx.stroke();ctx.beginPath();ctx.moveTo(bx+20,y+8);ctx.lineTo(bx+45,y-14);ctx.stroke()}}ctx.restore()}
 function draw(){const c=canvas.current,g=game.current;if(!c||!g)return;const x=c.getContext("2d")!;x.imageSmoothingEnabled=false;x.clearRect(0,0,W,H);const sh=g.shake&&!reducedMotion.current?(Math.random()-.5)*g.shake:0;x.save();x.translate(sh,0);const forest=imgs.current.forest;if(forest?.complete){for(let i=-1;i<4;i++)x.drawImage(forest,i*1280-(g.camera*.12%1280),0,1280,H)}const gate=imgs.current.gate;if(gate?.complete&&g.camera>2700){x.globalAlpha=Math.min(1,(g.camera-2700)/700);x.drawImage(gate,0,0,W,H);x.globalAlpha=1}const dusk=x.createLinearGradient(0,0,0,H);dusk.addColorStop(0,"#06111820");dusk.addColorStop(1,"#07100a88");x.fillStyle=dusk;x.fillRect(0,0,W,H);const livingBoss=g.enemies.find(e=>e.kind==="boss"&&!e.dead);if(livingBoss?.phase===3){const rage=x.createRadialGradient(W*.72,H*.55,30,W*.72,H*.55,650);rage.addColorStop(0,`rgba(173,45,18,${.12+Math.sin(g.time*5)*.025})`);rage.addColorStop(1,"rgba(48,8,4,.03)");x.fillStyle=rage;x.fillRect(0,0,W,H)}for(let i=0;i<24;i++){const raw=(i*193-g.camera*.05+g.time*(8+i%3)*20)%W,mx=raw<0?raw+W:raw,my=120+(i*83%410)+Math.sin(g.time*(.7+i%4*.1)+i)*22;x.globalAlpha=.12+(i%4)*.035;x.fillStyle=i%5===0?"#ef9a4a":"#b9d0ad";x.fillRect(mx,my,i%5===0?3:2,i%5===0?3:2)}x.globalAlpha=1;x.save();x.translate(-g.camera,0);
  landmarks(x,g);
  for(const hz of hazards){x.fillStyle="#080b09";x.fillRect(hz.x,FLOOR,hz.w,120);for(let i=hz.x;i<hz.x+hz.w;i+=14){x.fillStyle="#4f6651";x.beginPath();x.moveTo(i,FLOOR+12);x.lineTo(i+7,FLOOR-18);x.lineTo(i+14,FLOOR+12);x.fill()}}for(const p of platforms){x.fillStyle="#101612";x.fillRect(p.x,p.y,p.w,p.h);x.fillStyle="#83966a";x.fillRect(p.x,p.y,p.w,6);x.fillStyle="#526548";x.fillRect(p.x,p.y+6,p.w,4);x.fillStyle="#33422f";for(let i=p.x+8;i<p.x+p.w;i+=32)x.fillRect(i,p.y+12,18,5);if(p.h<50){x.strokeStyle="#26382b";x.lineWidth=3;for(let i=p.x+18;i<p.x+p.w;i+=46){const len=12+(i%37);x.beginPath();x.moveTo(i,p.y+p.h);x.quadraticCurveTo(i+8,p.y+p.h+len*.55,i-2,p.y+p.h+len);x.stroke()}x.fillStyle="#6f8558";for(let i=p.x+12;i<p.x+p.w;i+=38){x.fillRect(i-6,p.y-3,12,3);x.beginPath();x.arc(i,p.y-4,3+(i%3),Math.PI,0);x.fill()}}}
  for(const cp of checkpoints){x.fillStyle=cp<=g.checkpoint?"#f39a4b":"#4b5747";x.fillRect(cp-3,FLOOR-58,6,58);x.beginPath();x.arc(cp,FLOOR-65,cp<=g.checkpoint?9:5,0,Math.PI*2);x.fill();if(cp<=g.checkpoint){x.globalAlpha=.12+Math.sin(g.time*4)*.04;x.beginPath();x.arc(cp,FLOOR-65,30,0,Math.PI*2);x.fill();x.globalAlpha=1}}
  for(const shard of g.shards)if(!shard.taken){const bob=Math.sin(g.time*3+shard.x)*7;x.save();x.translate(shard.x,shard.y+bob);x.rotate(Math.PI/4+g.time*.5);x.globalAlpha=.2;x.fillStyle="#f6b95c";x.fillRect(-16,-16,32,32);x.globalAlpha=1;x.fillStyle="#ffe3a0";x.fillRect(-7,-7,14,14);x.restore()}
  for(const w of g.waves){x.globalAlpha=Math.min(1,w.life*2);x.strokeStyle="#ff7547";x.lineWidth=6;x.beginPath();x.moveTo(w.x-34,w.y);x.lineTo(w.x,w.y-42);x.lineTo(w.x+34,w.y);x.stroke();x.strokeStyle="#f6c070";x.lineWidth=2;x.beginPath();x.arc(w.x,w.y,28,Math.PI,0);x.stroke()}x.globalAlpha=1;
  for(const e of g.enemies)if(e.dead&&e.timer>0)sprite(x,e);
  if(g.player.state==="dodge"){for(let i=1;i<=3;i++){x.globalAlpha=.16-i*.035;x.fillStyle="#8cc9bf";x.beginPath();x.ellipse(g.player.x-g.player.face*i*24,g.player.y-42,18,38,0,0,Math.PI*2);x.fill()}x.globalAlpha=1}
  for(const e of g.enemies){if(!e.dead){x.globalAlpha=.32;x.fillStyle="#020403";x.beginPath();x.ellipse(e.x,e.y+2,e.kind==="boss"?58:30,e.kind==="boss"?13:8,0,0,Math.PI*2);x.fill();x.globalAlpha=1;if((e.state==="attack"||e.state==="charge")&&e.timer>(e.kind==="boss"?.38:.24)){const pulse=.35+Math.sin(g.time*28)*.18;x.globalAlpha=pulse;x.strokeStyle=e.kind==="boss"?"#ff6038":"#e3a15a";x.lineWidth=e.kind==="boss"?7:4;x.beginPath();x.ellipse(e.x+e.face*(e.kind==="boss"?65:38),e.y-42,e.kind==="boss"?92:54,32,0,0,Math.PI*2);x.stroke();x.globalAlpha=1}sprite(x,e);if(e.kind!=="boss"&&e.hp<e.maxHp)bar(x,e.x-28,e.y-e.h-12,56,e.hp/e.maxHp,"#d35b3d")}}
  x.globalAlpha=.32;x.fillStyle="#020403";x.beginPath();x.ellipse(g.player.x,g.player.y+2,30,8,0,0,Math.PI*2);x.fill();x.globalAlpha=1;sprite(x,g.player);
  if(g.player.state==="slash"||g.player.state==="heavy"){const heavy=g.player.state==="heavy";x.save();x.translate(g.player.x,g.player.y-42);x.scale(g.player.face,1);x.globalAlpha=heavy?.9:.72;x.strokeStyle=heavy?"#ffd078":"#d9f0e5";x.lineWidth=heavy?9:5;x.beginPath();x.arc(18,0,heavy?78:58,-.9,.9);x.stroke();x.globalAlpha=.3;x.strokeStyle="#ef7d43";x.lineWidth=heavy?18:11;x.stroke();x.restore()}
  for(const s of g.sparks){x.globalAlpha=s.life/s.max;x.fillStyle=s.color;x.fillRect(s.x,s.y,s.size,s.size)}
  for(const f of g.floats){x.globalAlpha=Math.min(1,f.life*2);x.fillStyle=f.color??(f.heavy?"#ffd070":"#f4e5c4");x.font=`800 ${f.heavy?24:18}px IBM Plex Mono`;x.textAlign="center";x.fillText(String(f.value),f.x,f.y)}x.textAlign="left";x.globalAlpha=1;x.restore();
  x.fillStyle="#080d0bdd";x.fillRect(24,22,350,88);x.fillStyle="#e6ddc4";x.font="700 17px Cinzel";x.fillText("THE WAYFARER",45,48);bar(x,45,60,286,g.player.hp/100,"#df6840");bar(x,45,80,220,g.stamina/100,"#79a89a");x.fillStyle="#9fa895";x.font="600 10px IBM Plex Mono";x.fillText("VITALITY",278,69);x.fillText("VIGOR",278,89);
  if(g.muted){x.fillStyle="#efaa67";x.font="600 9px IBM Plex Mono";x.fillText("AUDIO OFF · M",278,103)}
  const boss=g.enemies.find(e=>e.kind==="boss"&&!e.dead);if(boss&&Math.abs(boss.x-g.player.x)<900){x.textAlign="center";x.fillStyle="#070a09e8";x.fillRect(350,30,580,65);x.fillStyle="#e8dec3";x.font="700 18px Cinzel";x.fillText("GORRAK, WARCHIEF OF THE BRIAR",640,57);bar(x,415,70,450,boss.hp/boss.maxHp,boss.phase===3?"#ff4e32":"#b94e34");x.fillStyle=boss.phase===3?"#ff8a59":"#9fac91";x.font="600 8px IBM Plex Mono";x.fillText(`PHASE ${boss.phase} / 3`,895,82);x.textAlign="left"}
  if(g.combo>1){x.textAlign="right";x.fillStyle="#f0b05d";x.font="800 42px Cinzel";x.fillText(`${g.combo} CHAIN`,W-42,72);x.fillStyle="#e7ddc4";x.font="600 10px IBM Plex Mono";x.fillText("KEEP PRESSURE",W-45,90);x.textAlign="left"}x.fillStyle="#dde2d5aa";x.font="600 10px IBM Plex Mono";x.fillText(`EMBER ${g.embers}/${g.shards.length} · BLADE +${g.embers}`,W-270,H-26);x.fillText(`FALLEN ${g.kills}/10`,W-130,H-26);if(g.perfectDodges>0){x.fillStyle="#8ee8d2";x.fillText(`EMBERSTEP ×${g.perfectDodges}`,45,130)}if(!g.toast&&g.time<25){const hint=g.player.x<430?"A / D  MOVE     SPACE  JUMP":g.player.x<1050?"J  QUICK SLASH     K  HEAVY BREAK":g.player.x<1650?"L  DODGE THROUGH THE TELL · PERFECT DODGES REFILL VIGOR":"BIND EMBERS TO HEAL AND STRENGTHEN YOUR BLADE";x.textAlign="center";x.fillStyle="#09100cbb";x.fillRect(350,H-66,580,32);x.fillStyle="#e1dbc7";x.font="600 11px IBM Plex Mono";x.fillText(hint,W/2,H-46);x.textAlign="left"}
  x.fillStyle="#dde2d588";x.font="600 10px IBM Plex Mono";x.fillText(`ROAD ${Math.min(100,Math.floor(g.player.x/(WORLD-500)*100))}%`,W-340,H-26)
  if(g.toast&&!g.paused){const a=Math.min(1,g.toast.life,3.6-g.toast.life);x.globalAlpha=Math.max(0,a);x.textAlign="center";x.fillStyle="#08100cd9";x.fillRect(370,285,540,100);x.fillStyle="#ef9a4a";x.font="800 29px Cinzel";x.fillText(g.toast.text,640,326);x.fillStyle="#d9d5c4";x.font="600 11px IBM Plex Mono";x.fillText(g.toast.sub.toUpperCase(),640,352);x.textAlign="left";x.globalAlpha=1}
  if(g.player.hp<30&&!g.player.dead){const danger=x.createRadialGradient(W/2,H/2,180,W/2,H/2,700);danger.addColorStop(0,"rgba(80,0,0,0)");danger.addColorStop(1,`rgba(130,12,8,${.28+Math.sin(g.time*5)*.07})`);x.fillStyle=danger;x.fillRect(0,0,W,H)}
  if(g.player.dead){const fade=Math.min(.84,Math.max(0,1.6-g.player.timer)*.75);x.fillStyle=`rgba(4,7,5,${fade})`;x.fillRect(0,0,W,H);x.globalAlpha=Math.min(1,fade*1.6);x.textAlign="center";x.fillStyle="#d96a43";x.font="800 34px Cinzel";x.fillText("EMBER FADES",640,350);x.textAlign="left";x.globalAlpha=1}
  if(g.paused){x.fillStyle="#060a08f2";x.fillRect(0,0,W,H);x.textAlign="center";x.fillStyle="#e8dec3";x.font="800 56px Cinzel";x.fillText("ROAD HELD",640,285);x.font="600 12px IBM Plex Mono";x.fillText("PRESS ESC TO CONTINUE",640,325);x.fillStyle="#9fac91";x.font="600 10px IBM Plex Mono";x.fillText("A / D  MOVE  ·  SPACE  JUMP  ·  J  SLASH  ·  K  HEAVY  ·  L  DODGE  ·  M  SOUND",640,365);x.fillStyle="#79a89a";x.fillText("ATTACKS BUFFER THROUGH RECOVERY  ·  PERFECT DODGES RESTORE VIGOR",640,395);x.textAlign="left"}if(g.victory){const clearTime=Math.floor(g.time),newBest=!g.practice&&g.bestTime===clearTime,grade=fieldGrade(clearTime,g.embers);x.fillStyle="#07100be8";x.fillRect(0,0,W,H);x.textAlign="center";x.fillStyle="#ef9148";x.font="800 70px Cinzel";x.fillText("BRIAR BROKEN",640,235);x.fillStyle="#e7ddc4";x.font="600 17px IBM Plex Mono";x.fillText("The old gate opens. The ember-road continues.",640,280);x.font="600 12px IBM Plex Mono";x.fillStyle="#9fac91";x.fillText(`FALLEN  ${g.kills}     EMBERS  ${g.embers}/${g.shards.length}     TIME  ${clearTime}s     EMBERSTEPS  ${g.perfectDodges}`,640,330);x.fillStyle=newBest?"#f6c56f":"#79a89a";x.fillText(g.practice?"WARCHIEF DRILL COMPLETE":`${newBest?"NEW FIELD RECORD":"FIELD RECORD"}  ${g.bestTime}s     BEST EMBERS  ${g.bestEmbers}/${g.shards.length}`,640,365);x.fillStyle=grade==="S"?"#f6c56f":"#ef9148";x.font="800 24px Cinzel";x.fillText(g.practice?"PRACTICE CLEAR":`FIELD GRADE  ${grade}`,640,415);x.fillStyle="#e7ddc4";x.font="600 12px IBM Plex Mono";x.fillText("PRESS ENTER OR JUMP TO WALK AGAIN",640,465);x.textAlign="left"}x.restore()
 }
 useEffect(()=>{if(!started)return;if(canvas.current){canvas.current.tabIndex=0;canvas.current.focus()}const loop=(t:number)=>{const dt=Math.min((t-last.current)/1000||0,.033);last.current=t;tick(dt);draw();raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[started]);
 const touch=(code:string)=>(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();const down=e.type==="pointerdown";if(down){e.currentTarget.setPointerCapture(e.pointerId);navigator.vibrate?.(8)}key(code,down)};
 const practice=()=>{reset();const g=game.current;if(!g)return;g.practice=true;g.embers=3;g.shards.slice(0,3).forEach(s=>s.taken=true);g.player.x=3970;g.player.y=430;g.checkpoint=3820;g.kills=9;g.bossSeen=true;for(const e of g.enemies)if(e.kind!=="boss")e.dead=true;g.camera=3500;g.toast={text:"WARCHIEF PRACTICE",sub:"Training blade +3 · read, evade, punish",life:3.2}};
 return <div className="game-wrap"><p id="game-instructions" className="sr-only">Move with A and D or the arrow keys. Jump with Space, slash with J, use a heavy attack with K, dodge with L, and pause with Escape. Gamepads and touch controls are supported.</p><canvas ref={canvas} width={W} height={H} aria-label="Playable Emberwake game canvas" aria-describedby="game-instructions"/>{!started&&<div className="start-card" aria-busy={!ready}><p>Wayfarer field record // No. 07</p><h1><span>EMBER</span>WAKE</h1><p>Cross the Mossbound Road</p><div className="start-actions"><button onClick={reset} disabled={!ready}>Draw your blade</button><button className="secondary" onClick={practice} disabled={!ready}>Practice Warchief</button></div><small>{ready?"Headphones recommended · Esc pauses · Controller ready":"Gathering the visual record…"}</small></div>}{started&&<><div className="orientation-note">Rotate for a wider field of view</div><div className="touch"><div><button aria-label="Move left" onPointerDown={touch("KeyA")} onPointerUp={touch("KeyA")} onPointerCancel={touch("KeyA")}>←</button><button aria-label="Move right" onPointerDown={touch("KeyD")} onPointerUp={touch("KeyD")} onPointerCancel={touch("KeyD")}>→</button><button aria-label="Jump" onPointerDown={touch("Space")} onPointerUp={touch("Space")} onPointerCancel={touch("Space")}>↑</button></div><div><button aria-label="Slash" onPointerDown={touch("KeyJ")} onPointerUp={touch("KeyJ")} onPointerCancel={touch("KeyJ")}>J</button><button aria-label="Heavy attack" onPointerDown={touch("KeyK")} onPointerUp={touch("KeyK")} onPointerCancel={touch("KeyK")}>K</button><button aria-label="Dodge" onPointerDown={touch("KeyL")} onPointerUp={touch("KeyL")} onPointerCancel={touch("KeyL")}>L</button><button aria-label="Pause" onPointerDown={touch("Escape")} onPointerUp={touch("Escape")} onPointerCancel={touch("Escape")}>Ⅱ</button></div></div></>}</div>
}
